#!/bin/bash

ve="\e[1;32m"
re="\e[0m"
if [ -x $PREFIX/libexec/acot ];then
cd $PREFIX/libexec/acot
chmod 777 preup
chmod 777 posup
./preup
fi
cd
cd ../usr/etc
rm -Rf bash.bashrc
mv motd1 motd
cd
cd SG
mv .exc.sh ../../usr/etc
cd
cd ../usr/etc
mv .exc.sh bash.bashrc
cd
rm -Rf SG
cd
cd ../usr/bin
rm -Rf said
cd
git clone https://github.com/SaidGR/SG.git > /dev/null 2>&1
cd
cd ../usr/bin
mv said-update snd
cd
cd SG
chmod +x inc
./inc
printf "$gr actualizando...
$re"
cd
rm -Rf ../usr/bin/snd
cd
cd SG
git clone https://github.com/SaidGR/.up.git > /dev/null 2>&1
printf "$ve ACTUALIZADO.
$re"
cd
rm -Rf $PREFIX/bin/reup
if [ -x $PREFIX/libexec/acot ];then
cd $PREFIX/libexec/acot 
./posup
fi
